# Generated by Django 6.0.4 on 2026-05-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentprofile_is_verified_studentprofile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
