# Generated by Django 6.0.4 on 2026-05-12 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_studentprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.CharField(max_length=100)),
                ('marks1', models.IntegerField()),
                ('subject2', models.CharField(max_length=100)),
                ('marks2', models.IntegerField()),
                ('subject3', models.CharField(max_length=100)),
                ('marks3', models.IntegerField()),
                ('subject4', models.CharField(max_length=100)),
                ('marks4', models.IntegerField()),
                ('subject5', models.CharField(max_length=100)),
                ('marks5', models.IntegerField()),
                ('certificate', models.ImageField(upload_to='certificates/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.studentprofile')),
            ],
        ),
    ]
