# Generated by Django 6.0.4 on 2026-05-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='description',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='required_skills',
        ),
    ]
